const HttpStatusCode = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOT_EXECUTE: 210,
  NOT_SUCCESSFULL: 220,
  WAIT_FOR_APPROVEL: 300,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  CONFLICT: 409,
  EXPECTATIONFAILED: 417,
};
const GenericMessages = {
  OK: "Ok",
  BOOKED: "booked",
  INTERNAL_SERVER_ERROR: "Internal server error",
  TOKEN_IS_INVALID: "Token is invalid",
  ID_NOT_FOUND: "Id not found",
  ID_IS_INVALID: "Id is invalid",
  NOT_AUTHORIZED: "You are not authorized to access this call.",
  EMAIL_SENDING_FAILED: "Email sending failed, Please try again",
  EMAIL_NOT_FOUND: "Email doesn't belong to any account",
  TOKEN_NOT_EXIST: "Token does not exist",
  ADMIN_ALLOWED: "Only admins are authorized to access this route",
  MASTER_ALLOWED: "Master account is allowed to access this route",
  USER_ALLOWED: "User account doesnot have access to this route",
  APIKEY_INVALID: "API key is invalid",
  APIKEY_VALID: "API key is verified",
  INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
  INVALID_EMAIL: "Invalid email",
  ACCOUNT_SUSPENDED: "You are suspended, Please contact with Admin",
  ACCOUNT_DELETED: "Your account deleted, Please contact with Admin",
  KYC_FETCHED: "KYC fetched successfully.",
  KYC_STATUS_UPDATED: "User KYC status updated successfully",
  NO_PASSWORD: "Password not provided",
  UNABLE_TO_ADD_DATA: "unable to add data",
  UNABLE_TO_SEND_EMAIL: "Unable to send email",
  NOT_FOUND: "Data not found",
  COULD_NOT_FIND_EMAIL: "Could not find email",
  COULD_NOT_FIND_USER: "Could not find User",
  COULD_NOT_FIND_TRANSACTION: "Could not find Transaction",
  RECORD_NOT_FOUND: "Record not found",
  ACCEPT_TERM_AND_CONDITION: "Accepted Terms & conditions.",
  FAILED_TO_SAVE_RECORD: "Failed to save record",
  SUCCESS_FETCHED_WITHDRAWS: "Withdraws fetched successfully",
  SUCCESS_FETCHED_COINS: "Coins fetched successfully",
  INSUFICIENT_BALANCE:
    "Could not perform this action due to insufficient balance",
  EMAIL_ALREADY_EXIST: "Email address already exists",
  SUCCESS_FETCHED_BALANCE: "Balance fetched successfully",
  SUCCESS_FETCHED_DATA: "Data fetched successfully",
  EMAIL_TOKEN_IS_INVALID: "Email token is invalid",
  WEBHOOK_NOT_EXECUTABLE: "This webhook is not executable",
  TRANSACTION_RECEIVED: "Transaction received",
  UNABLE_TO_SAVE_DUMB_DATA: "Unable to save dumb data",
  INVALID_WEBHOOK_HEADERS: "Invalid webhook headers",
  MIN_WITHDRAW_AMOUNT_LIMIT:
    "Withdraw amount must be greater than or equal to 100",
  MAX_WITHDRAW_AMOUNT_LIMIT:
    "Withdraw amount must be lesser than or equal to 100000000",
  COULD_NOT_UPDATE_TRANSACTION: "Could not update the Transaction",
  UNABLE_TO_FIND_RECORD: "Unable to find record",
  UNABLE_TO_DELETE_RECORD: "Unable to delete record",
  RECORD_FETCHED_SUCCESSFULLY: "Record fetch successfully",
  RECORD_ALREADY_EXISTS: "Record already exists",
  PERMISSION_DENIED: "The operation you are attempting is not permitted.",
  DATA_CHANGE_ERROR:
    "Data might have changed. Please refresh the page and try again",
  AUTHORIZATION_FAILURE: "You are not authorized to access this call.",
  ACCESS_DENIED: "Access Denied. No refresh token provided.",
  SUSPENDED_ALERT: "You are suspended, please contact support.",
  DELETION_ALERT: "You are deleted, please contact support.",
  AUTHORIZATION_ACTION_FAILURE: "You are not authorized to do this action",
  SYMBOL: "symbol",
  COINID: "coinId",
  INVALID_PASSWORD: "Password is invalid",
  ROUTES_NOT_FOUND: "Route Not Found",
  SERVER_ERROR_DUE_TO_MANY_REQUESTS:
    "You sent too many requests. Please wait a while then try again",
  TOKEN_NOT_EXISTS: "Token doesn't exist",
  LOGIN_SUCCESSFULLY: "Login successfully",
};

const GENERIC_CONSTANTS = {
  CRYPTO_WITHDRAW_FEE: 3.5,
  DATE_TIME_FORMAT: "YYYY-MM-DD HH:mm:ss",
  DATE_FORMAT: "YYYY-MM-DD",
  _DATE_FORMAT: "MMMM DD",
  _DATE_TIME_FORMAT: "YYYY-MM-DDTHH:mm",
  OK: "Ok",
  MONTHS: "months",
  DISABLED: "disabled",
  ENHABLED: "enabled",
  TWO_FA_DISABLED: "twoFaDisabled",
  LEVEL: "level",
  PRICE: "price",
  INFO: "Info",
  ERROR: "Error",
  CUSTOM_ERROR: "Custom Error",
  NAME: "name",
  IP: "ip",
  SUM_SUB: "SumSub",
  MONOOVA: "Monoova",
  CALENDLY: "Calendly",
  MAILER: "Mailer",
  COIN_RANKING: "Coin Ranking",
  FIRE_BLOCK_API: "Fire Block Api",
  GEO_LOCATION_IP: "Geo Location Ip",
  RECAPTCHA: "Recaptcha",
  FUNCTION: "function",
  _SUPER: "super",
  _SUPERVISOR: "supervisor",
  _ADMIN: "admin",
  _BUY: "buy",
  _SELL: "sell",
  _WITHDRAW: "withdraw",
  _DEPOSIT: "deposit",
  NEBULA_PAYMENTS_PTY_LTD: "Nebula Payments Pty Ltd",
  SOMETHING_WENT_WRONG_TRY_LATER:
    "Something went wrong on our end. Please try again later",
  REJECT: "Reject",
  DAY: "day",
  MONTH: "month",
  CREDIT: "credit",
  NPP: "npp",
  IDC: "idc",
  _ID: "_id",
  WITHDRAWS: "withdraws",
  BALANCE: "balance",
  AMOUNT: "amount",
  BANKS: "banks",
  HEX: "hex",
  HASH_DIGEST: "sha512",
  WAITING_TO_BOOK: "waiting to book",
  BTC: "btc",
  _BTC: "BTC",
  _ETH: "ETH",
  USD: "usd",
  _USDT: "TRX_USDT_S2UZ",
  DEPOSIT_RECEIVED: "DepositReceived",
  _ERROR: "error",
  FAIL: "fail",
  DEVELOPMENT: "development",
  HOURS: "hours",
  BASE32: "base32",
  UNKNOWN_ERROR: "Unknown Error",
  AUTHORIZATION: "authorization",
  BEARER: "Bearer",
  REFRESH_TOKEN: "refreshToken",
  DEFAULT_PORT: 4000,
  AUTHORIZATION_CODE: "authorization_code",
};

const UserConstants = {
  USER: "user",
  BANK: "bank",
  USER_CREATED: "userCreated",
  USER_UPDATED: "userUpdated",
  USER_DELETED: "userDeleted",
  USER_KYC: "userKyc",
  KYC: "kyc",
  PROFILE: "profile",
  ADMIN: "admin",
  VERIFIED_ACCOUNT: "verifiedAccount",
  FORGET_PASSWORD: "forgetPassword",
  RESET_PASSWORD: "resetPassword",
  UPDATE_PROFILE: "updateProfile",
  ACCEPTED_TERM: "AcceptTerms",
  CHANGE_PASSWORD: "changePassword",
  CHANGE_EMAIL_REQUEST: "changeEmailRequest",
  CHANGE_EMAIL: "changeEmail",
  USER_BANK_CREATED: "userBankCreated",
  ADMIN_RESET_MAIL: "adminResentEmail",
};

const UserMessages = {
  FAILED_TO_FIND_USER: "Failed to find user",
  FAILED_TO_SAVE_USER: "Failed to save user",
  FAILED_TO_LOGIN_USER: "Failed to login user",
  EMAIL_ALREADY_EXIST:
    "An account with this email address is already registered",
  REGISTER_ACCOUNT_SUCCESS: "Your account created successfully",
  USERS_FETCHED_SUCCESS: "Users fetched successfully",
  USER_DETAILS_FETCHED_SUCCESS: "User details fetched successfully",
  REFERENCES_NOT_SAME: "References could not be same",
};

const DealMessages = {
  FAILED_TO_FIND_DEAL: "Failed to find deal",
  FAILED_TO_SAVE_DEAL: "Failed to save deal",
  CREATE_SUCCESS: "Deal created successfully",
  FETCHED_SUCCESS: "Deal(s) fetched successfully",
};

const InstallmentMessages = {
  FAILED_TO_FIND_INSTALLMENT: "Failed to find installment",
  FAILED_TO_SAVE_INSTALLMENT: "Failed to save installment",
  CREATE_SUCCESS: "Installment created successfully",
  FETCHED_SUCCESS: "Installment(s) fetched successfully",
};

const Roles = {
  USER: "user",
  SUPER_ADMIN: "superAdmin",
  SUPERVISOR: "supervisor",
};

const OFFSET_LIMIT = 10;

const apiMethodes = {
  POST: "post",
  GET: "get",
};

const authApi = {
  register: "/auth/register",
  login: "/auth/login",
};

const adminApi = {
  fetchUsers: "/auth/register",
  login: "/auth/login",
};

const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export {
  HttpStatusCode,
  GenericMessages,
  GENERIC_CONSTANTS,
  UserConstants,
  UserMessages,
  Roles,
  OFFSET_LIMIT,
  DealMessages,
  InstallmentMessages,
  apiMethodes,
  authApi,
  monthNames,
};
